name: "FiatChamp"
url: "https://github.com/wubbl0rz/FiatChamp"
description: "Connect your FIAT (uconnect) car to Home Assistant. ðŸš—"
services:
    - "mqtt:need"
version: "1.0.56"
slug: "fiat_champ"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""
  RefreshInterval: 15
  Debug: false
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  RefreshInterval: int
  Debug: bool
arch:
  - amd64
  - armv7
