name: "FiatChamp"
url: "https://github.com/wubbl0rz/FiatChamp"
description: "Connect your FIAT (uconnect) car to Home Assistant. ðŸš—"
services:
    - "mqtt:want"
version: "2.0.14"
image: "ghcr.io/wubbl0rz/image-{arch}-fiat-champ"
slug: "fiat_champ"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""
  RefreshInterval: 15
  ConvertKmToMiles: false
  Debug: false
  AutoRefreshBattery: false
  AutoRefreshLocation: false
  EnableDangerousCommands: false
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  ConvertKmToMiles: bool
  RefreshInterval: int
  Debug: bool
  AutoRefreshBattery: bool
  AutoRefreshLocation: bool
  EnableDangerousCommands: bool
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
arch:
  - amd64
  - armv7
