name: "FiatChamp"
url: "https://github.com/wubbl0rz/FiatChamp"
description: "Connect your FIAT (uconnect) car to Home Assistant. ðŸš—"
services:
    - "mqtt:want"
version: "3.0.8"
homeassistant_api: true
image: "ghcr.io/wubbl0rz/image-{arch}-fiat-champ"
slug: "fiat_champ"
init: false
discovery: 
    - "mqtt"
options:
  FiatUser: ""
  FiatPw: ""
  FiatPin: ""
  Brand: "Fiat"
  RefreshInterval: 15
  ConvertKmToMiles: false
  Debug: false
  AutoRefreshBattery: false
  AutoRefreshLocation: false
  EnableDangerousCommands: false
  CarUnknownLocation: "away"
  StartDelaySeconds: 1
schema:
  FiatUser: str
  FiatPw: password
  FiatPin: password?
  Brand: list(Fiat|Ram|Jeep|Dodge|AlfaRomeo)
  Region: list(Europe|America)
  ConvertKmToMiles: bool
  RefreshInterval: int
  Debug: bool
  AutoRefreshBattery: bool
  AutoRefreshLocation: bool
  EnableDangerousCommands: bool
  OverrideMqttUser: str?
  OverrideMqttPw: password?
  OverrideMqttServer: str?
  OverrideMqttPort: int?
  CarUnknownLocation: str
  StartDelaySeconds: int?
arch:
  - amd64
  - armv7
